// DOM element refs for the UI shell, queried once at module load.

const $ = (sel: string) => document.querySelector(sel)!

export const domRefs = {
  roomList: $('#room-list') as HTMLElement,
  roomHeader: $('#room-header') as HTMLElement,
  roomNameEl: $('#room-name') as HTMLElement,
  roomInfoBar: $('#room-info-bar') as HTMLElement,
  roomMembers: $('#room-members') as HTMLElement,
  roomsToggle: $('#rooms-toggle') as HTMLElement,
  roomsHeader: $('#rooms-header') as HTMLElement,
  agentList: $('#agent-list') as HTMLElement,
  noRoomState: $('#no-room-state') as HTMLElement,
  agentArea: $('#agent-area') as HTMLElement,
  chatArea: $('#chat-area') as HTMLElement,
  pinnedMessagesDiv: $('#pinned-messages') as HTMLElement,
  workspaceBar: $('#workspace-bar') as HTMLElement,
  workspacePane: $('#workspace-pane') as HTMLElement,
  workspaceContent: $('#workspace-content') as HTMLElement,
  workspaceLabel: $('#workspace-label') as HTMLElement,
  workspaceAddRow: $('#workspace-add-row') as HTMLElement,
  artifactInput: $('#artifact-input') as HTMLInputElement,
  btnArtifactSubmit: $('#btn-artifact-submit') as HTMLElement,
  messagesDiv: $('#messages') as HTMLElement,
  chatForm: $('#chat-form') as HTMLFormElement,
  chatInput: $('#chat-input') as HTMLInputElement,
  modeSelector: $('#mode-selector') as HTMLSelectElement,
  pauseToggle: $('#btn-pause-toggle') as HTMLButtonElement,
  roomModeInfo: $('#room-mode-info') as HTMLElement,
  nameModal: $('#name-modal') as HTMLDialogElement,
  nameForm: $('#name-form') as HTMLFormElement,
  roomModal: $('#room-modal') as HTMLDialogElement,
  roomForm: $('#room-form') as HTMLFormElement,
  agentModal: $('#agent-modal') as HTMLDialogElement,
  agentForm: $('#agent-form') as HTMLFormElement,
  sidebar: $('#sidebar') as HTMLElement,
  btnCollapseSidebar: $('#btn-collapse-sidebar') as HTMLElement,
  settingsHeader: $('#settings-header') as HTMLElement,
  settingsToggle: $('#settings-toggle') as HTMLElement,
  settingsList: $('#settings-list') as HTMLElement,
  agentsHeader: $('#agents-header') as HTMLElement,
  agentsToggle: $('#agents-toggle') as HTMLElement,
  toolsHeader: $('#tools-header') as HTMLElement,
  toolsToggle: $('#tools-toggle') as HTMLElement,
  toolsList: $('#tools-list') as HTMLElement,
  skillsHeader: $('#skills-header') as HTMLElement,
  skillsToggle: $('#skills-toggle') as HTMLElement,
  skillsList: $('#skills-list') as HTMLElement,
  artifactTypeSelect: $('#artifact-type-select') as HTMLSelectElement,
  ollamaStatusDot: document.getElementById('ollama-status-dot') as HTMLElement,
  ollamaDashboard: document.getElementById('ollama-dashboard') as HTMLDialogElement,
  ollamaDashboardClose: document.getElementById('ollama-dashboard-close') as HTMLButtonElement,
  ollamaUrlSelect: $('#ollama-url-select') as HTMLSelectElement,
  ollamaUrlInput: $('#ollama-url-input') as HTMLInputElement,
  btnOllamaUrlAdd: $('#btn-ollama-url-add') as HTMLElement,
  btnOllamaUrlDelete: $('#btn-ollama-url-delete') as HTMLElement,
} as const
